//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHaml.BackEnds.Boo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHaml.BackEnds.Boo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing attributes: BinaryExpression expected but get {0}..
        /// </summary>
        internal static string AttributesParse_BinaryExpressionExpected {
            get {
                return ResourceManager.GetString("AttributesParse_BinaryExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing attributes: {0}.
        /// </summary>
        internal static string AttributesParse_BooParserError {
            get {
                return ResourceManager.GetString("AttributesParse_BooParserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing attributes: ExpressionStatement expected but get {0}..
        /// </summary>
        internal static string AttributesParse_ExpressionStatementExpected {
            get {
                return ResourceManager.GetString("AttributesParse_ExpressionStatementExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing attributes: Statement count is greater then one..
        /// </summary>
        internal static string AttributesParse_StatementGreaterThenOne {
            get {
                return ResourceManager.GetString("AttributesParse_StatementGreaterThenOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing attributes: Expected Literal- or ReferenceExpression but get {0}..
        /// </summary>
        internal static string AttributesParse_UnexpectedAttributeExpression {
            get {
                return ResourceManager.GetString("AttributesParse_UnexpectedAttributeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing attributes: Black has no or more then one statement..
        /// </summary>
        internal static string AttributesParse_UnexpectedBlockStatementCount {
            get {
                return ResourceManager.GetString("AttributesParse_UnexpectedBlockStatementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing attributes: Expected HashLiteral- or BlockExpression but get {0}..
        /// </summary>
        internal static string AttributesParse_UnexpectedExpression {
            get {
                return ResourceManager.GetString("AttributesParse_UnexpectedExpression", resourceCulture);
            }
        }
    }
}
