//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHaml.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHaml.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing attributes.
        /// </summary>
        internal static string AttributesParseError {
            get {
                return ResourceManager.GetString("AttributesParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when compiling the file: {0}.
        /// </summary>
        internal static string CompilationError {
            get {
                return ResourceManager.GetString("CompilationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing tag.
        /// </summary>
        internal static string ErrorParsingTag {
            get {
                return ResourceManager.GetString("ErrorParsingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal Indentation: Only {0} space character(s) allowed as indentation.
        /// </summary>
        internal static string IllegalIndentationSpaces {
            get {
                return ResourceManager.GetString("IllegalIndentationSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal Indentation: Only tabs allowed as indentation.
        /// </summary>
        internal static string IllegalIndentationTabs {
            get {
                return ResourceManager.GetString("IllegalIndentationTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplateBaseType must inherit from CompiledTemplate.
        /// </summary>
        internal static string InvalidTemplateBaseType {
            get {
                return ResourceManager.GetString("InvalidTemplateBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant Failure.
        /// </summary>
        internal static string InvariantFail {
            get {
                return ResourceManager.GetString("InvariantFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not assignable to ITemplateCompiler.
        /// </summary>
        internal static string NotAssignableToITemplateCompiler {
            get {
                return ResourceManager.GetString("NotAssignableToITemplateCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Not Null Object.
        /// </summary>
        internal static string ObjectNull {
            get {
                return ResourceManager.GetString("ObjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string argument &quot;{0}&quot; cannot be empty.
        /// </summary>
        internal static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error on line {0}: {1}: &quot;{2}&quot;.
        /// </summary>
        internal static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplateCompiler type {0} not found.
        /// </summary>
        internal static string TemplateCompilerTypeNotFound {
            get {
                return ResourceManager.GetString("TemplateCompilerTypeNotFound", resourceCulture);
            }
        }
    }
}
